import turtle
import random

bob = turtle.Turtle()

points = 0
lives = 3


def Italy():
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.fillcolor("green")
    bob.begin_fill()
    for i in range(2):
        bob.fd(90)
        bob.rt(90)
        bob.fd(180)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.fd(90)
    bob.pendown()
    bob.fillcolor("white")
    bob.begin_fill()
    for i in range(2):
        bob.fd(90)
        bob.rt(90)
        bob.fd(180)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.fd(90)
    bob.pendown()
    bob.fillcolor("red")
    bob.begin_fill()
    for i in range(2):
        bob.fd(90)
        bob.rt(90)
        bob.fd(180)
        bob.rt(90)
    bob.end_fill()

    turtle.done()
def France():
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(90)
        bob.rt(90)
        bob.fd(180)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.fd(90)
    bob.pendown()
    bob.fillcolor("white")
    bob.begin_fill()
    for i in range(2):
        bob.fd(90)
        bob.rt(90)
        bob.fd(180)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.fd(90)
    bob.pendown()
    bob.fillcolor("red")
    bob.begin_fill()
    for i in range(2):
        bob.fd(90)
        bob.rt(90)
        bob.fd(180)
        bob.rt(90)
    bob.end_fill()
def Germany():
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.fillcolor("black")
    bob.begin_fill()
    for i in range(2):
        bob.fd(320)
        bob.rt(90)
        bob.fd(90)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.rt(90)
    bob.fd(90)
    bob.lt(90)
    bob.pendown()
    bob.fillcolor("red")
    bob.begin_fill()
    for i in range(2):
        bob.fd(320)
        bob.rt(90)
        bob.fd(90)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.rt(90)
    bob.fd(90)
    bob.lt(90)
    bob.pendown()
    bob.fillcolor("yellow")
    bob.begin_fill()
    for i in range(2):
        bob.fd(320)
        bob.rt(90)
        bob.fd(90)
        bob.rt(90)
    bob.end_fill()
def Finland():
    bob.penup()
    bob.goto(-150, 60)
    bob.pendown()
    for i in range(2):
        bob.fd(350)
        bob.rt(90)
        bob.fd(250)
        bob.rt(90)
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(50)
        bob.rt(90)
        bob.fd(250)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.goto(-150,-40)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(350)
        bob.rt(90)
        bob.fd(50)
        bob.rt(90)
    bob.end_fill()
def Poland():
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.fillcolor("white")
    bob.begin_fill()
    for i in range(2):
        bob.fd(350)
        bob.rt(90)
        bob.fd(125)
        bob.rt(90)
    bob.end_fill()

    bob.penup()
    bob.rt(90)
    bob.fd(125)
    bob.lt(90)
    bob.pendown()
    bob.fillcolor("red")
    bob.begin_fill()
    for i in range(2):
        bob.fd(350)
        bob.rt(90)
        bob.fd(125)
        bob.rt(90)
    bob.end_fill()
def Greece():
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.pencolor("blue")
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(20)
        bob.rt(90)
        bob.fd(20)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.fd(30)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(20)
        bob.rt(90)
        bob.fd(20)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.rt(90)
    bob.fd(30)
    bob.lt(90)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(20)
        bob.rt(90)
        bob.fd(20)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.bk(30)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(20)
        bob.rt(90)
        bob.fd(20)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.fd(50)
    bob.lt(90)
    bob.fd(30)
    bob.rt(90)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(120)
        bob.rt(90)
        bob.fd(10)
        bob.rt(90)
    bob.end_fill()
    bob.rt(90)
    bob.fd(20)
    bob.lt(90)
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(120)
        bob.rt(90)
        bob.fd(10)
        bob.rt(90)
    bob.end_fill()
    bob.rt(90)
    bob.fd(20)
    bob.lt(90)
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(120)
        bob.rt(90)
        bob.fd(10)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.rt(90)
    bob.fd(10)
    bob.rt(90)
    bob.fd(50)
    bob.lt(90)
    bob.fd(10)
    bob.lt(90)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(170)
        bob.rt(90)
        bob.fd(10)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.rt(90)
    bob.fd(20)
    bob.lt(90)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for i in range(2):
        bob.fd(170)
        bob.rt(90)
        bob.fd(10)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.pencolor("black")
    for i in range(2):
        bob.fd(170)
        bob.rt(90)
        bob.fd(90)
        bob.rt(90)
def China():
    bob.penup()
    bob.goto(-80, 100)
    bob.pendown()
    bob.pencolor("red")
    bob.fillcolor("red")
    bob.begin_fill()
    for i in range(2):
        bob.fd(350)
        bob.rt(90)
        bob.fd(250)
        bob.rt(90)
    bob.end_fill()
    bob.penup()
    bob.goto(-60, 60)
    bob.pendown()
    bob.pencolor("yellow")
    bob.fillcolor("yellow")
    bob.begin_fill()
    for i in range(5):
        bob.fd(50)
        bob.rt(144)
    bob.end_fill()
    bob.penup()
    bob.goto(-10, 80)
    bob.pendown()
    bob.pencolor("yellow")
    bob.fillcolor("yellow")
    bob.begin_fill()
    for i in range(5):
        bob.fd(10)
        bob.rt(144)
    bob.end_fill()
    bob.penup()
    bob.goto(0, 65)
    bob.pendown()
    bob.pencolor("yellow")
    bob.fillcolor("yellow")
    bob.begin_fill()
    for i in range(5):
        bob.fd(10)
        bob.rt(144)
    bob.end_fill()
    bob.penup()
    bob.goto(0, 50)
    bob.pendown()
    bob.pencolor("yellow")
    bob.fillcolor("yellow")
    bob.begin_fill()
    for i in range(5):
        bob.fd(10)
        bob.rt(144)
    bob.end_fill()
    bob.penup()
    bob.goto(-10, 35)
    bob.pendown()
    bob.pencolor("yellow")
    bob.fillcolor("yellow")
    bob.begin_fill()
    for i in range(5):
        bob.fd(10)
        bob.rt(144)
    bob.end_fill()
def UAE():
    bob.fillcolor("red")
    bob.begin_fill()
    bob.fd(70)
    bob.rt(90)
    bob.fd(120)
    bob.rt(90)
    bob.fd(70)
    bob.rt(90)
    bob.fd(120)
    bob.rt(90)
    bob.fd(70)
    bob.end_fill()
    bob.fillcolor("green")
    bob.begin_fill()
    bob.fd(140)
    bob.rt(90)
    bob.fd(40)
    bob.rt(90)
    bob.fd(140)
    bob.rt(90)
    bob.fd(40)
    bob.end_fill()
    bob.fillcolor("black")
    bob.penup()
    bob.rt(180)
    bob.fd(120)
    bob.pendown()
    bob.begin_fill()
    bob.lt(90)
    bob.fd(140)
    bob.lt(90)
    bob.fd(40)
    bob.lt(90)
    bob.fd(140)
    bob.lt(90)
    bob.fd(40)
    bob.end_fill()






    turtle.done







#List with flags.
flags = [Italy, France, Germany, Finland, Poland, Greece, China, UAE,]

while lives>0 and len(flags) >0:
    bob.reset()
    bob.speed(200)
    flag = random.choice(flags)
    flag()
    answer = input("Guess da flag.")

    if answer == flag.__name__:
        print("GOOD JOBBB!!!!!111!!!!111!1")
        points = points +100
        print("Points:", points)
        print("Lives", lives)
        flags.remove(flag)

    else:
        print("u dumb boi dat wrong")
        if points <0:
            points = points -1
        else:
            points = 0
        lives = lives -1
        print("Points:", points)
        print("Lives:", lives)
        flags.remove(flag)
        print("You win!")





#Italy()
#France()
#Germany()
#Finland()
#Poland()
#Greece()
#China()
#UAE()

